<?php
$weight_selected = empty( $_POST['weight'] ) ? empty( $page->level1 ) ? '0.0.0' : "$page->level1.$page->level2.$page->level3" : $_POST['weight'];
$link_selected = empty( $_POST['link'] ) ? empty( $page->link ) ? '' : $page->link : $_POST['link'];
$slug_selected = empty( $_POST['slug'] ) ? empty( $page->slug ) ? '' : $page->slug : $_POST['slug'];
$title_selected = empty( $_POST['title'] ) ? empty( $page->title ) ? '' : $page->title : $_POST['title'];
$subtitle_selected = empty( $_POST['subtitle'] ) ? empty( $page->subtitle ) ? '' : $page->subtitle : $_POST['subtitle'];
$content_selected = empty( $_POST['content'] ) ? empty( $page->content ) ? '' : $page->content : $_POST['content'];
$hook_selected = empty( $_POST['hooks_id'] ) ? empty( $page->hooks_id ) ? '' : $page->hooks_id : $_POST['hooks_id'];
?>
<form action="admin/pages/create" method="post">
    <div class="tabbable">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#1" data-toggle="tab">Titles</a></li>
			<li><a href="#2" data-toggle="tab">Content</a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="1">
				<p class="span1">
					<label>Weight:</label>
					<input name="weight" value="<?php echo $weight_selected; ?>" />
				</p>
				<p class="span3">
					<label>Link name:</label>
					<input name="link" value="<?php echo $link_selected; ?>" />
				</p>
				<p class="span5">
					<label>Link url-format-slug: ( updated if there )</label>
					<input name="slug" value="<?php echo $slug_selected; ?>" />
				</p>
				<p class="span6">
					<label>Title:</label>
					<input name="title" value="<?php echo $title_selected; ?>" />
				</p>
				<p class="span7">
					<label>Subtitle:</label>
					<input name="subtitle" value="<?php echo $subtitle_selected; ?>" />
				</p>
				<p class="span3">
					<label>hook:</label>
					<select name="hooks_id">
						<?php
						foreach ( $hooks as $hook )
						{
							?>
							<option<?php _::esel( $hook->id, $hook_selected ); ?> value="<?php echo $hook->id; ?>"><?php echo $hook->hook; ?></option>
							<?php
						}
						?>
					</select>
				</p>
			</div>
			<div class="tab-pane" id="2">
				<p class="span8">
					<label>Content:</label>
					<textarea class="ckeditor" name="content"><?php echo $content_selected; ?></textarea>
				</p>
			</div>
		</div>
		<p class="navbar-fixed-bottom">
			<button class="btn btn-success" type="submit"><i class="icon-ok icon-white"></i> Save</button>
		</p>
	</div>
</form>
<?php
View::partial( 'ckeditor' );
