
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<ul class="nav">
				<li><a href="pages">Pages</a></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Tables<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="tables/change/hooks">Hooks</a></li>
						<li><a href="tables/change/pages">Pages</a></li>
						<li><a href="tables/change/roles">Roles</a></li>
						<li><a href="tables/change/templates">Templates</a></li>
						<li><a href="tables/change/users">Users</a></li>
					</ul>
				</li>
				<li><a href="<?php echo $controller_name; ?>/logout">Logout ?</a></li>
			</ul>
		</div>
	</div>
</div>
