
<ul>
	<?php
	foreach ( Load::model( 'templates' )->noDeleted() as $template )
	{
		?>
		<li>
			<?php echo $template->template; ?>
			<ul>
				<?php
				foreach ( Load::model( 'hooks' )->byFk( 'templates_id', $template->id ) as $hook )
				{
					?>
					<li>
						<?php echo $hook->hook; ?>
						<ul>
							<?php
							foreach ( Load::model( 'pages' )->byFk( 'hooks_id', $hook->id, 'level1,level2,level3' ) as $page )
							{
								if ( ! $page->link ) $page->link = $page->slug;
								?>
								<li>
									<?php echo "$page->level1.$page->level2.$page->level3"; ?>
									<a href="admin/pages/index/<?php echo $page->id; ?>"><?php echo $page->link; ?></a>
									<a href="/<?php echo $page->slug; ?>" title="view <?php echo $page->slug; ?>?" target="_blank"><?php echo _img::eicon( 7, 10, 'view' ); ?></a>
									<a href="admin/pages/delete/<?php echo $page->id; ?>" onclick="if ( ! confirm( 'Sure?' ) ) return false" title="delete <?php echo $page->slug; ?>?"><?php echo _img::eicon( 1, 11, 'delete' ); ?></a>

								</li>
								<?php
							}
							?>
						</ul>
					</li>
					<?php
				}
				?>
			</ul>
		</li>
		<?php
	}
	?>
</ul>
